#!/bin/sh

# used by the hooks-functions of iniramfs-tools
DESTDIR="/run/initramfs"
verbose="y"

# remount /run executable because we use it to run our shutdown script
mount -o remount,rw /var/run/ /run/

# Otherwise systemd-shutdown cannot execute /run/initramfs/shutdown
mount -o remount,exec /run

# create directories
for d in etc bin sbin proc ; do
  mkdir $DESTDIR/$d || true 2>/dev/null
done

# copy busybox and dependencies to /run/initramfs
# remove this line until the bug is fixed
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953563
#. /usr/share/initramfs-tools/hooks/zz-busybox

# copy plymouth
. /usr/share/initramfs-tools/hooks/plymouth

# copy systemctl needed for final shutdown
copy_exec /bin/systemctl

# copy shutdown script, this script will be executed later by systemd-shutdown
cp /lib/systemd/lernstick-shutdown $DESTDIR/shutdown

# mount proc
mount -o bind /proc $DESTDIR/proc
